server.port=8081

vector.dimension = 512
ignite.address=127.0.0.1:10800
ignite.cache.name=vectors

search.mode=service

# actuator + prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.tags.application=vindex

# ???????????/?????????? HTTP-?????????? (??? p50/p95/p99 ??????)
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.slo.http.server.requests=5ms,10ms,25ms,50ms,100ms,250ms,500ms,1s,2s

# ??????? ?????? stats ? ????? ???????? ??? coverage
vindex.metrics.poll-ms=2000
vindex.total-partitions=32
vindex.metrics.enabled=true