x-java-opts: &java-opts >-
  --add-opens=java.base/jdk.internal.misc=ALL-UNNAMED
  --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
  --add-opens=java.base/java.io=ALL-UNNAMED
  --add-opens=java.base/java.nio=ALL-UNNAMED
  --add-opens=java.base/java.util=ALL-UNNAMED
  --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
  --add-opens=java.base/java.lang=ALL-UNNAMED
  --add-opens=java.management/sun.management=ALL-UNNAMED
  --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED
  --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED
  --add-exports=java.base/sun.nio.ch=ALL-UNNAMED
  --add-exports=java.management/com.sun.jmx.mbeanserver=ALL-UNNAMED
  --add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED
  --add-exports=java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED

x-node-common: &node-common
  restart: unless-stopped
  build: { context: ., target: "${NODE_TARGET:-ignite-node}" }
  image: vindex-node:local
  network_mode: host
  volumes:
    - ./docker/config-2vm/ignite-config.xml:/config/ignite-config.xml:ro
    - ./jfr:/jfr
  healthcheck:
    test: ["CMD-SHELL", "nc -z $$IGNITE_LOCAL_HOST $$IGNITE_THIN_PORT || exit 1"]
    interval: 5s
    timeout: 3s
    retries: 30


x-node-env: &node-env
  JVM_OPTS: ${NODE_JVM_OPTS}
  INDEX_TYPE: ${INDEX_TYPE:-JVECTOR_INDEX}
  IGNITE_LOCAL_HOST: ${IGNITE_LOCAL_HOST}
  VM1_IP: ${VM1_IP}
  VM2_IP: ${VM2_IP}

services:
  node-a:
    <<: *node-common
    container_name: ${NODE_PREFIX}-a
    environment:
      <<: *node-env
      IGNITE_CONSISTENT_ID: ${NODE_PREFIX}-a
      IGNITE_DISCO_PORT: "47500"
      IGNITE_COMM_PORT:  "47100"
      IGNITE_THIN_PORT:  "10800"

  node-b:
    <<: *node-common
    container_name: ${NODE_PREFIX}-b
    environment:
      <<: *node-env
      IGNITE_CONSISTENT_ID: ${NODE_PREFIX}-b
      IGNITE_DISCO_PORT: "47501"
      IGNITE_COMM_PORT:  "47101"
      IGNITE_THIN_PORT:  "10801"
    depends_on: [node-a]

  vector-server:
    profiles: ["server"]
    restart: unless-stopped
    build: { context: ., target: vector-server }
    environment:
      IGNITE_ADDRESS: ${VM1_IP}:10800,${VM1_IP}:10801,${VM2_IP}:10800,${VM2_IP}:10801
      JAVA_TOOL_OPTIONS: *java-opts
      JDK_JAVA_OPTIONS: "-Xmx512m"
    volumes: [ "${DATA_DIR:-./data}:/data" ]
    ports: ["8081:8081"]

  bench:
    profiles: [ "bench" ]
    build: { context: ., target: vector-server }
    entrypoint: [ "java","-Xmx1g",
                  "-Dloader.main=ru.nsu.fit.sberlab.vectorindex.vectorserver.benchmark.BenchmarkMain",
                  "-jar","/app/app.jar" ]
    environment:
      IGNITE_ADDRESS: ${VM1_IP}:10800,${VM1_IP}:10801,${VM2_IP}:10800,${VM2_IP}:10801

      INDEX_TYPE: ${INDEX_TYPE:-JVECTOR_INDEX} #Edit in .env

      DATABASE_PATH: /data/dataset.csv
      QUERIES_PATH: /data/quieries.csv
      RESULTS_PATH: /data/results.csv
      HDF5_PATH: /data/coco-i2i-512-angular.hdf5

      NEIGHBOR_COUNT: "10"
      PRINT_MISMATCH: "false"

      BENCHMARK_MODE: ${BENCHMARK_MODE:-OUR_DATASET}  #Edit in .env
      LOAD_DATABASE: "true"

      HIGHLOAD_MAX_IN_FLIGHT: "64"
      HIGHLOAD_TARGET_RPS: "100"
      HIGHLOAD_WARMUP_SECONDS: "10"
      HIGHLOAD_TEST_SECONDS: "60"

      HIGHLOAD_SWEEP_START_RPS: "100"
      HIGHLOAD_SWEEP_MAX_RPS: "600"
      HIGHLOAD_SWEEP_RPS_STEP: "100"
      HIGHLOAD_SWEEP_PAUSE_SECONDS: "5"

      N_CLIENTS_COUNT: "8"
      N_CLIENTS_WARMUP_SECONDS: "10"
      N_CLIENTS_TEST_SECONDS: "60"

      VINDEX_METRICS_ENABLED: "false"

      JAVA_TOOL_OPTIONS: *java-opts
    volumes:
      - ${DATA_DIR:-./data}:/data

  prometheus:
    profiles: [ "metrics" ]
    image: prom/prometheus:v2.53.1
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  grafana:
    profiles: [ "metrics" ]
    image: grafana/grafana:11.1.4
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_SERVER_ROOT_URL: https://sberschool2026-vm11.sberlab.nsu.ru/grafana/
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/vindex.json
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on: [ "prometheus" ]
    restart: unless-stopped

  edge:
    profiles: [ "metrics" ]
    image: nginx:alpine
    restart: unless-stopped
    ports: [ "80:80" ]
    volumes:
      - ./docker/nginx/2vm.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: [ grafana, vector-server ]