server {
    listen 80;
    server_name sberschool2026-vm11.sberlab.nsu.ru;

    location /grafana/ {
        proxy_pass http://grafana:3000;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade    $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location = /vectors/stats {
        proxy_pass http://vector-server:8081/vectors/stats;
    }

    location / { return 404; }
}